import turtle

turtle.setup(640, 480)
turtle.speed(2)

turtle.showturtle()
turtle.hideturtle()
turtle.showturtle()
turtle.goto(0, 100)
turtle.write("HEYYY")

turtle.forward(200)
turtle.right(90)
turtle.forward(200)
turtle.right(90)
turtle.forward(200)
turtle.right(90)
turtle.forward(200)
turtle.setheading(45)
turtle.forward(20)
turtle.heading()
turtle.penup()
turtle.forward(100)
turtle.pendown()
turtle.left(90)
turtle.forward(100)
turtle.circle(100)
turtle.dot()
turtle.pensize(10)
turtle.pencolor("green")
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.bgcolor('gray')


turtle.reset()
turtle.clear()
turtle.clearscreen()
